#ifndef __SPMP_H__
#define __SPMP_H__

#include <stdint.h>

#define MCATCH_CMD_SYSTEM_SET_SYSINFO		0x001
#define MCATCH_CMD_SYSTEM_GET_SYSINFO		0x002
#define MCATCH_CMD_SYSTEM_POWER_OFF		0x003 /* canonical */
#define MCATCH_CMD_SYSTEM_CAL_VOLTAGE		0x004

typedef struct {
    uint32_t sec;
    uint32_t min;
    uint32_t hour;
    uint32_t day;
    uint32_t month;
    uint32_t year;
} mcatch_system_time_t;

/* out: mcatch_system_time_t */
#define MCATCH_CMD_SYSTEM_SYS_TIME_GET		0x005

#define MCATCH_CMD_SYSTEM_SYS_TIME_SET		0x006
#define MCATCH_CMD_SYSTEM_ALARM_GET		0x007
#define MCATCH_CMD_SYSTEM_ALARM_SET		0x008
#define MCATCH_CMD_SYSTEM_ALARMTIME_DISABLE	0x009 /* canonical */
#define MCATCH_CMD_SYSTEM_SUSPEND_ENABLE	0x00A /* probably canonical */
#define MCATCH_CMD_SYSTEM_SUSPEND_DISABLE	0x00B /* canonical */
#define MCATCH_CMD_SYSTEM_TVOUT_ENABLE		0x00C
#define MCATCH_CMD_SYSTEM_TVOUT_DISABLE		0x00D
#define MCATCH_CMD_SYSTEM_SYS_UPDATE		0x00E	/* careful there! */
#define MCATCH_CMD_SYSTEM_SYS_TIME_SET_NO_RTC	0x00F
#define MCATCH_CMD_SYSTEM_IS_SD_PLUGGED_IN	0x010
#define MCATCH_CMD_SYSTEM_SPEAKER_OFF		0x011
#define MCATCH_CMD_SYSTEM_SPEAKER_ON		0x012
#define MCATCH_CMD_SYSTEM_KEY_LOCK		0x013
#define MCATCH_CMD_SYSTEM_KEY_UNLOCK		0x014
#define MCATCH_CMD_SYSTEM_MMISUSPEND_ENABLE	0x015 /* canonical */
#define MCATCH_CMD_SYSTEM_MMISUSPEND_DISABLE	0x016 /* canonical */
/* #define MCATCH_CMD_SYSTEM_NOP		0x017 */
#define MCATCH_CMD_SYSTEM_SYS_DETECT_START	0x018
#define MCATCH_CMD_SYSTEM_SYS_DETECT_STOP	0x019
#define MCATCH_CMD_SYSTEM_AUDIO_VOLUME_SET	0x01A
#define MCATCH_CMD_SYSTEM_SET_PANEL_BRIGHTNESS	0x01B
#define MCATCH_CMD_SYSTEM_EQ_SET		0x01C
#define MCATCH_CMD_SYSTEM_DOLBY_SW		0x01D
#define MCATCH_CMD_SYSTEM_SET_PWR_OFF_SEC	0x01E
#define MCATCH_CMD_SYSTEM_FM_INIT		0x01F
#define MCATCH_CMD_SYSTEM_FM			0x020
#define MCATCH_CMD_SYSTEM_FM_HW_STOP		0x021
#define MCATCH_CMD_SYSTEM_FM_CHG_BAND_LIMIT	0x022
#define MCATCH_CMD_SYSTEM_FM_SEARCH_TOP_LVL	0x023
#define MCATCH_CMD_SYSTEM_NAND_CACHE_FLUSH	0x024
#define MCATCH_CMD_SYSTEM_PWR_OFF_TIME_SET	0x025
#define MCATCH_CMD_SYSTEM_SET_PWR_OFF_MODE_ZERO	0x026
/* #define MCATCH_CMD_SYSTEM_INVALID		0x027 */
#define MCATCH_CMD_SYSTEM_NAND_HIDDEN_READ	0x028
#define MCATCH_CMD_SYSTEM_NAND_HIDDEN_WRITE	0x029
/* #define MCATCH_CMD_SYSTEM_NOP		0x02A */
/* #define MCATCH_CMD_SYSTEM_NOP_FAIL		0x02B */
#define MCATCH_CMD_SYSTEM_MMI_START		0x02C /* canonical */
#define MCATCH_CMD_SYSTEM_MMI_MSG_READY		0x02D /* canonical */
#define MCATCH_CMD_SYSTEM_SET_LONGKEY_LATENCY	0x02E
#define MCATCH_CMD_SYSTEM_ARM_CLOCK_SPEED_UP	0x02F
#define MCATCH_CMD_SYSTEM_HWND_REG		0x030
#define MCATCH_CMD_SYSTEM_SYS_VERSION_GET	0x031
#define MCATCH_CMD_SYSTEM_GET_WAKEUP_REASON	0x032
#define MCATCH_CMD_SYSTEM_SYS_REBOOT		0x033
/* #define MCATCH_CMD_SYSTEM_INVALID		0x034 */
#define MCATCH_CMD_SYSTEM_RESUME_LCD		0x035
#define MCATCH_CMD_SYSTEM_SUSPEND_LCD		0x036
#define MCATCH_CMD_SYSTEM_CHANGE_SYS_FREQ_33	0x037
#define MCATCH_CMD_SYSTEM_CHANGE_SYS_FREQ_0A	0x038
#define MCATCH_CMD_SYSTEM_LOCK_FREQ		0x039
#define MCATCH_CMD_SYSTEM_UNLOCK_FREQ		0x03A
/* #define MCATCH_CMD_SYSTEM_INVALID		0x03B .. 0x05F */
#define MCATCH_CMD_SYSTEM_GET_IOTRAPS_BIT0	0x060

#define MCATCH_CMD_DSC_START			0x101
#define MCATCH_CMD_DSC_STOP			0x102
#define MCATCH_CMD_DSC_ZOOM			0x103
#define MCATCH_CMD_DSC_PREVIEW_BRIGHTNESS_SET	0x104
#define MCATCH_CMD_DSC_OPTION_SET		0x105
#define MCATCH_CMD_DSC_CAPTURE			0x106

#define MCATCH_CMD_IMAGE_INFO_GET		0x301 /* probably canonical */
#define MCATCH_CMD_PLAYBACK_START		0x302 /* canonical */
/* #define MCATCH_CMD_IMAGE_INVALID		0x303 */
#define MCATCH_CMD_PLAYBACK_ZOOM_PAN		0x304 /* canonical */
#define MCATCH_CMD_IMAGE_PLAY_ZOOM_PAN		0x305
/* #define MCATCH_CMD_INVALID			0x306 */
#define MCATCH_CMD_IMAGE_FREE_IMAGE		0x307
#define MCATCH_CMD_IMAGE_FREE_IMAGE2		0x308
#define MCATCH_CMD_IMAGE_JPEG_DECODE_CODEC_LOAD	0x309
#define MCATCH_CMD_IMAGE_JPEG_DECODE_CODEC_RELEASE	0x30A
#define MCATCH_CMD_IMAGE_DISPLAY_FLIP		0x30B

#define MCATCH_CMD_MEDIA_RECORD			0x401
#define MCATCH_CMD_MEDIA_RECORD_STOP		0x402
#define MCATCH_CMD_MEDIA_INFO_GET		0x403
#define MCATCH_CMD_MEDIA_START			0x404
#define MCATCH_CMD_MEDIA_STOP			0x405
#define MCATCH_CMD_MEDIA_PAUSE			0x406
#define MCATCH_CMD_MEDIA_RESUME			0x407
#define MCATCH_CMD_MEDIA_SEEK			0x408
#define MCATCH_CMD_MEDIA_AUDIO_BG_START		0x409 /* canonical */
#define MCATCH_CMD_MEDIA_AUDIO_BG_STOP		0x40A /* canonical */
#define MCATCH_CMD_MEDIA_GET_FRAME		0x840B /* unimplemented? */

#define MCATCH_CMD_FS_DEV_MOUNT			0x601 /* probably canonical */
#define MCATCH_CMD_FS_DEV_UNMOUNT		0x602 /* canonical */
#define MCATCH_CMD_FS_DEV_FORMAT		0x603
#define MCATCH_CMD_FS_DEV_INFO_GET		0x604
#define MCATCH_CMD_FS_MULTI_FILE_GET_NUM	0x8605
#define MCATCH_CMD_FS_MULTI_FILE_FIND		0x606
#define MCATCH_CMD_FS_SET_DIR			0x607
#define MCATCH_CMD_FS_GET_DIR			0x8608
#define MCATCH_CMD_FS_MKDIR			0x609
#define MCATCH_CMD_FS_RMDIR			0x60A
#define MCATCH_CMD_FS_FILE_INFO_GET		0x60B
/* #define MCATCH_CMD_FS_INVALID		0x60C */
#define MCATCH_CMD_FS_DELETE			0x60D
/* #define MCATCH_CMD_FS_INVALID		0x60E .. 0x610 */
#define MCATCH_CMD_FS_OPEN			0x8611
#define MCATCH_CMD_FS_CLOSE			0x612
#define MCATCH_CMD_FS_OPEN_EXT			0x8612
#define MCATCH_CMD_FS_READ			0x613
/* #define MCATCH_CMD_FS_INVALID		0x614 */
#define MCATCH_CMD_FS_WRITE			0x615
/* #define MCATCH_CMD_FS_INVALID		0x616 */
#define MCATCH_CMD_FS_SEEK			0x617
#define MCATCH_CMD_FS_COPY_FILE			0x618
#define MCATCH_CMD_FS_TELL			0x619
#define MCATCH_CMD_FS_FORCE_SET_REFRESH		0x61A
#define MCATCH_CMD_FS_FIND_FILE_NO_IN_DIR	0x61B

#define MCATCH_CMD_USB_MODE_SET			0x901 /* canonical */
#define MCATCH_CMD_USB_SET_CLASS_NAME		0x902
#define MCATCH_CMD_USB_SAVE_POWER_ON		0x903 /* canonical */
#define MCATCH_CMD_USB_SAVE_POWER_OFF		0x904 /* probably canonical */

#define MCATCH_CMD_GFX_MODE_SET			0xB01 /* canonical */
#define MCATCH_CMD_GFX_MODE_GET			0xB02 /* probably canonical */
/* #define MCATCH_CMD_GFX_INVALID		0xB03 */
#define MCATCH_CMD_GFX_CLEAR_FLIP_IF_TV_OFF	0xB04
#define MCATCH_CMD_GFX_CLEAR_IF_TV_OFF		0xB05
#define MCATCH_CMD_GFX_SET_FB_FORMAT		0xB06
#define MCATCH_CMD_GFX_UNKNOWN_1		0xB07
#define MCATCH_CMD_GFX_UNKNOWN_2		0xB08
#define MCATCH_CMD_GFX_UNKNOWN_3		0xB09 /* SK8607: same as 0xB07 */
#define MCATCH_CMD_GFX_UNKNOWN_4		0xB0A /* SK8607: same as 0xB08 */
#define MCATCH_CMD_GFX_SET_TV_WAIT_FRAME_END	0xB0B
#define MCATCH_CMD_GFX_SET_OSD_BUFFER_MIX_ALPHA	0xB0C
/* #define MCATCH_CMD_GFX_NOP			0xB0D */
#define MCATCH_CMD_GFX_SET_DISABLE_DOUBLE_BUFFER_COPY	0xB0E
#define MCATCH_CMD_GFX_SET_BACKLIGHT_ENABLED	0xB0F
#define MCATCH_CMD_GFX_LCD_SET_OSD_CLIP_AREA	0xB10

#define MCATCH_CMD_GM_INIT_GAME_SYSTEM		0xD01
/* #define MCATCH_CMD_GM_NOP			0xD02 */
#define MCATCH_CMD_GM_SET_CRTL_KEY_VALUE_AND_RESUME	0xD03
#define MCATCH_CMD_GM_EXIT_GAME			0xD04
#define MCATCH_CMD_GM_SAVE_STATE		0xD05
#define MCATCH_CMD_GM_ENABLE_GAME_KEYBOARD	0xD06
#define MCATCH_CMD_GM_ENABLE_MW_KEYBOARD	0xD07
#define MCATCH_CMD_GM_SET_LONGKEY_LATENCY	0xD08
#define MCATCH_CMD_GM_LOAD_STATE		0xD09

#endif
