#
# libspmp8k
#
# tools makefile
#
#

all:	build-bingtools build-chksum build-el2mmp build-packboot build-romboy build-sprdump 

clean:
	make -C bingtools clean
	make -C chksum clean
	make -C elf2mmp clean
	make -C packboot clean
	make -C romboy clean
	make -C sprdump clean

build-bingtools:
	make -C bingtools

build-chksum:
	make -C chksum

build-el2mmp:
	make -C elf2mmp

build-packboot:
	make -C packboot

build-romboy:
	make -C romboy

build-sprdump:
	make -C sprdump

