#!/bin/sh
# Power on hub and mount internal flash to /spmp once available.
mountdev='/dev/disk/by-id/usb-USB_DISK_MASS_STORAGE48F0_aaaaaaaa-0:0'
hub="001:001"

sudo hubpower "$hub" bind
while ! test -e "$mountdev"
do
	usleep 300000
done
sudo mount -o uid=1000 "$mountdev" /spmp
