#
# libspmp8k
#
# demos makefile
#
#

all: build-rgbgame build-keydemo build-doom110 build-z26

clean:
	make -C rgbgame clean
#	make -C uarttest clean
	make -C keydemo clean
	make -C doom110 clean
	make -C z26 clean
	make -C audio clean
	make -C diag clean

#build-uarttest:
#	make -C uarttest

build-rgbgame:
	make -C rgbgame

build-keydemo:
	make -C keydemo

build-doom110:
	make -C doom110

build-z26:
	make -C z26

