#
# libspmp8k
#
# demos makefile
#
#

all: build-rgbgame build-libgame build-keydemo build-doom110

clean:
	make -C rgbgame clean
#	make -C uarttest clean
	make -C libgame clean
	make -C keydemo clean
	make -C doom110 clean

#build-uarttest:
#	make -C uarttest

build-rgbgame:
	make -C rgbgame

build-libgame:
	make -C libgame

build-keydemo:
	make -C keydemo

build-doom110:
	make -C doom110


